name: Gaming_website

on: 
  push:
    branches:
      - main

jobs:
  build_docker_image_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: building frontend image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/entertainment_frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/entertainment_frontend:latest

      # - name: building backend image
      #   working-directory: ./backend
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/entertainment_fast_backend:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/entertainment_fast_backend:latest

      # - name: building agent ai image
      #   working-directory: ./agent_ai/Entertainment-app
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/entertainment_agent_ai:latest -f Dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/entertainment_agent_ai:latest

      # - name: building express backend image
      #   working-directory: ./express_backend
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/entertainment_express_backend:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/entertainment_express_backend:latest
